resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: github
      path: BatelT/pipelines-simple-steps
pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        integrations:
            - name: slack    
        execution:
           onSuccess:
             - echo $MY_MESSAGE
             - echo “running CI for master”
             - send_notification notifySlack --text "Maven build completed for $res_app_gitRepo_path at $res_app_gitRepo_gitProvider_url"
           onFailure:
             - send_notification notifySlack --text "Maven build FAILED for $res_app_gitRepo_path at $res_app_gitRepo_gitProvider_url"
