resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: github
      path: BatelT/pipelines-simple-steps
pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
          integrations:
            - name: slack    
        execution:
          onExecute:
            - send_notification slack --text "Hello"
     
