resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: github
      path: BatelT/pipelines-simple-steps
pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        integrations:
            - name: slack    
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo “running CI for master”
            - send_notification notifySlack --text "built docker image 123.12.111.173:8081/docker-local/demo:$PIPELINE_NAME.$RUN_NUMBER"
